# Site settings
title: Un blog tout simple avec Jekyll et sur Jekyll
description: "Un blog tout simple avec Jekyll et sur Jekyll."
url: "https://crazyden.github.io/grise/"
author:
  name: ""
  email: ""
  url: "https://crazyden.github.io/grise/"

# Build settings
baseurl: /grise # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
